import Dexie, { type Table } from 'dexie';

/**
 * Dexie database layer for persistent learning artifacts.
 *
 * Design goals:
 * - typed schemas
 * - scalable keys for multi-video / future multi-session learning
 * - migration-ready structure (explicit versioning)
 * - small reusable helpers (get/put queries)
 */

// ---------- Common helpers ----------

export function nowMs() {
  return Date.now();
}

export type ISODateString = string;

export type BaseEntity = {
  id: string;
  videoId?: string; // optional because we may want global/session-only rows later
  createdAt: number;
  updatedAt: number;
  // schemaVersion allows future non-migration changes at the row level.
  schemaVersion: number;
};

export type RevisionGrade = 'again' | 'hard' | 'good' | 'easy';

// ---------- Transcripts ----------

export type TranscriptRow = BaseEntity & {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  metadata: {
    totalDuration: number;
    chunkCount: number;
    fetchedAt: number;
  };
  // Stored as an array of transcript chunks (enhanced chunk is used by RAG)
  chunks: Array<{
    id: string;
    text: string;
    startTime: number;
    endTime: number;
    duration: number;
    index: number;
  }>;
};

// ---------- Embeddings / Semantic chunks ----------

export type EmbeddingRow = BaseEntity & {
  videoId: string;
  model: string;
  // semantic chunk id
  semanticChunkId: string;
  vector: number[];
};

export type SemanticChunkRow = BaseEntity & {
  videoId: string;
  semanticChunkId: string;
  text: string;
  startTime: number;
  endTime: number;
  transcriptChunkIds: string[];
  embedding?: {
    model: string;
    // keep only the semanticChunkId->embedding row in embeddings table
    // this optional field is for partial caches.
  };
};

// ---------- Notes / Chapters ----------

export type NoteRow = BaseEntity & {
  videoId: string;
  type: 'concise' | 'detailed' | 'interview' | 'revision' | 'custom';
  title: string;
  // markdown-style content
  content: string;
  format: 'markdown' | 'plain';
  tags: string[];
  isPinned: boolean;
  // timestamp anchors allow review notes to link back to parts of transcript
  timestampAnchors?: Array<{ startTime: number; endTime?: number; label?: string }>;
};

export type ChapterRow = BaseEntity & {
  videoId: string;
  title: string;
  // For navigation we store full list + also index fields.
  chapters: Array<{
    id: string;
    title: string;
    startTime: number;
    endTime: number;
    summary: string;
    keyPoints: string[];
  }>;
};

// ---------- Revision: flashcards / quizzes / scheduling ----------

export type FlashcardRow = BaseEntity & {
  videoId: string;
  // stable identity across generations
  flashcardId: string;
  front: string;
  back: string;
  difficulty: 'easy' | 'medium' | 'hard';

  // SM-2 scheduling fields
  nextReviewDate: number;
  intervalDays: number;
  repetitions: number;
  easeFactor: number;
  lastReviewedAt?: number;

  // For analysis later
  source: {
    noteId?: string;
    chapterId?: string;
    semanticChunkIds?: string[];
    generationMode?: 'beginner' | 'interview';
  };
};

export type QuizRow = BaseEntity & {
  videoId: string;
  quizId: string;
  mode: 'beginner' | 'interview' | 'revision';
  title: string;
  questions: Array<{
    id: string;
    question: string;
    options: string[];
    correctAnswerIndex: number;
    explanation: string;
    difficulty: 'easy' | 'medium' | 'hard';
    timestamp?: number;
  }>;
};

export type FlashcardResponseRow = BaseEntity & {
  // one row per grading event
  videoId: string;
  responseId: string;
  flashcardId: string;
  gradedAt: number;
  grade: RevisionGrade;
  // derived scheduling outcome snapshot
  resulting: {
    nextReviewDate: number;
    intervalDays: number;
    repetitions: number;
    easeFactor: number;
  };
};

export type RevisionProgressRow = BaseEntity & {
  videoId: string;
  // store per-artifact progress for analytics + resume.
  artifactType: 'flashcards' | 'quizzes';
  artifactId: string;

  // counts & last review time
  lastReviewedAt?: number;
  totalReviews: number;
  correctCount: number;
  // optional streak
  streak?: number;
};

export type AnalyticsRow = BaseEntity & {
  videoId?: string;
  kind:
    | 'learning_event'
    | 'ai_generation'
    | 'revision_completion'
    | 'future_reserved';
  payload: any;
};

// ---------- Dexie schema ----------

export class StudyflowDB extends Dexie {
  transcripts!: Table<TranscriptRow, string>;
  semanticChunks!: Table<SemanticChunkRow, string>; // primary key semanticChunkId
  embeddings!: Table<EmbeddingRow, string>; // primary key: `${semanticChunkId}|${model}`

  notes!: Table<NoteRow, string>;
  chapters!: Table<ChapterRow, string>;

  flashcards!: Table<FlashcardRow, string>;
  quizzes!: Table<QuizRow, string>;
  flashcardResponses!: Table<FlashcardResponseRow, string>;
  revisionProgress!: Table<RevisionProgressRow, string>;

  analytics!: Table<AnalyticsRow, string>;

  constructor() {
    super('studyflow');

    // schemaVersion increments are done via db.version(x).stores({ ... })
    // Dexie will run migrations for existing users.
    this.version(1).stores({
      // Primary keys are explicit via Table generic; Dexie uses string keys.
      transcripts: 'id, videoId, updatedAt',

      semanticChunks: 'id, videoId, startTime, endTime, updatedAt',
      // embeddings indexed by videoId+semanticChunkId+model
      embeddings: 'id, videoId, semanticChunkId, model, updatedAt',

      notes: 'id, videoId, type, createdAt, updatedAt, isPinned',
      chapters: 'id, videoId, updatedAt',

      flashcards: 'id, videoId, nextReviewDate, intervalDays, easeFactor, difficulty',
      quizzes: 'id, videoId, mode, updatedAt',
      flashcardResponses: 'id, videoId, flashcardId, gradedAt',
      revisionProgress: 'id, videoId, artifactType, artifactId, updatedAt',

      analytics: 'id, videoId, kind, createdAt',
    });
  }
}

let _db: StudyflowDB | null = null;

export function getDb(): StudyflowDB {
  if (!_db) {
    _db = new StudyflowDB();
  }
  return _db;
}

export async function ensureDbReady() {
  await getDb().open();
}

// ---------- Repository helpers (minimal, reusable) ----------



export const DbIds = {
  transcript: (videoId: string) => `transcript|${videoId}`,
  semanticChunk: (videoId: string, semanticChunkId: string) => `chunk|${videoId}|${semanticChunkId}`,
  embedding: (videoId: string, semanticChunkId: string, model: string) =>
    `embed|${videoId}|${semanticChunkId}|${model}`,
  note: (videoId: string, noteId: string) => `note|${videoId}|${noteId}`,
  chapterSet: (videoId: string) => `chapters|${videoId}`,
  flashcard: (videoId: string, flashcardId: string) => `flashcard|${videoId}|${flashcardId}`,
  quiz: (videoId: string, quizId: string) => `quiz|${videoId}|${quizId}`,
  flashcardResponse: (videoId: string, responseId: string) => `resp|${videoId}|${responseId}`,
  revisionProgress: (videoId: string, artifactType: string, artifactId: string) =>
    `progress|${videoId}|${artifactType}|${artifactId}`,
  analytics: (id: string) => `analytics|${id}`,
};

// ---------- CRUD convenience ----------

export async function upsertTranscript(row: Omit<TranscriptRow, 'id' | 'createdAt' | 'updatedAt' | 'schemaVersion'> & {
  id?: string;
}): Promise<string> {
  const db = getDb();
  const id = row.id ?? DbIds.transcript(row.videoId);
  const t: TranscriptRow = {
    ...(row as any),
    id,
    createdAt: (row as any).createdAt ?? nowMs(),
    updatedAt: nowMs(),
    schemaVersion: (row as any).schemaVersion ?? 1,
  };
  await db.transcripts.put(t);
  return id;
}

