import type { TranscriptChunk } from '@/types/transcript';
import { parseYouTubeTranscript } from './transcript.parser';

type ExtractResult =
  | {
      status: 'success';
      chunks: TranscriptChunk[];
      enhancedChunks: any[];
      totalDuration: number;
      metadata: {
        videoId: string;
        language: string;
        isAutoGenerated: boolean;
        fetchedAt: number;
        totalDuration: number;
        chunkCount: number;
      };
    }
  | { status: 'not-available'; reason: string }
  | { status: 'error'; reason: string };

function normalizeLanguage(lang: string | null | undefined): string {
  const v = (lang ?? '').trim();
  return v || 'en';
}



function extractVideoIdFromLocation(): string | null {
  try {
    const url = new URL(window.location.href);
    const v = url.searchParams.get('v');
    return v || null;
  } catch {
    return null;
  }
}

function getTranscriptAvailabilityFromPage(videoId: string): { available: boolean; language?: string } {

  // We attempt multiple strategies in order to avoid brittle single-selector failures.

  // Strategy A: youtube.com often contains an embedded JSON in scripts.
  const scripts = Array.from(document.querySelectorAll('script'));
  let foundInScripts = false;
  for (const s of scripts) {
    const text = s.textContent;
    if (!text) continue;

    // Common pattern: "playerCaptionsTracklistRenderer".
    if (!text.includes('playerCaptionsTracklistRenderer')) continue;

    // If the page has caption tracks, it will likely have caption renderer with tracklist.
    if (text.includes('tracks') || text.includes('captionTracks')) {
      foundInScripts = true;
      break;
    }
  }

  // Strategy B: DOM presence of transcript/CC button elements.
  // Avoid deep DOM traversal: only check top-level markers.
  const anyCaptionMarkers = document.querySelectorAll(
    '[aria-label*="captions" i], [aria-label*="subtitles" i]'
  );
  const markerCount = anyCaptionMarkers ? anyCaptionMarkers.length : 0;

  // Strategy C: YouTube watch pages sometimes include "ytInitialPlayerResponse".
  const playerResponse = (window as any).__ytInitialPlayerResponse;
  const tracklist = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  const trackCount = Array.isArray(tracklist) ? tracklist.length : 0;

  console.log('[YT StudyFlow][transcript] availability probes:', {
    videoId,
    foundInScripts,
    markerCount,
    trackCount,
    hasPlayerResponse: !!playerResponse,
  });

  if (foundInScripts) return { available: true };
  if (markerCount > 0) return { available: true };
  if (trackCount > 0) {
    return {
      available: true,
      language: tracklist?.[0]?.languageCode?.toString(),
    };
  }

  // fallback unknown
  return { available: false };
}


async function fetchCaptionTrackFromBaseUrl(baseUrl: string): Promise<any[] | null> {
  // Base URL may include formatting; we try to fetch and parse.
  // We support VTT and XML-ish caption payloads.
  try {
    const res = await fetch(baseUrl, { credentials: 'omit' });
    if (!res.ok) return null;
    const contentType = res.headers.get('content-type') || '';
    const text = await res.text();
    if (!text) return null;

    // 1) VTT parsing
    const isVtt = contentType.includes('text/vtt') || text.includes('WEBVTT');
    if (isVtt) {
      return parseVttCues(text);
    }

    // 2) XML parsing fallback
    // YouTube caption XML usually contains <text start="..." dur="...">
    const xmlText = text;
    return parseYouTubeXmlCues(xmlText);
  } catch {
    return null;
  }
}

function parseVttCues(vttText: string): Array<{ start: number; duration: number; text: string }> {
  // Minimal, robust VTT parsing.
  const cues: Array<{ start: number; duration: number; text: string }> = [];
  const lines = vttText.replace(/\r/g, '').split('\n');
  let i = 0;

  const parseTimestamp = (ts: string): number | null => {
    // mm:ss.mmm or hh:mm:ss.mmm
    const parts = ts.split(':');
    if (parts.length === 2) {
      const [mm, restRaw] = parts;
      const rest = restRaw ?? '0';
      const secParts = rest.split('.');
      const seconds = Number(secParts[0]);
      const ms = Number(secParts[1] ?? '0');

      if (!Number.isFinite(seconds) || !Number.isFinite(Number(mm))) return null;
      return Number(mm) * 60 + seconds + ms / 1000;
    }
    if (parts.length === 3) {
      const [hh, mm, restRaw] = parts;
      const rest = restRaw ?? '0';
      const secParts = rest.split('.');

      const seconds = Number(secParts[0]);
      const ms = Number(secParts[1] ?? '0');
      if (!Number.isFinite(seconds) || !Number.isFinite(Number(hh)) || !Number.isFinite(Number(mm))) return null;
      return Number(hh) * 3600 + Number(mm) * 60 + seconds + ms / 1000;
    }
    return null;
  };

  while (i < lines.length) {
    const line = lines[i]!.trim();
    // skip header/comments
    if (!line || line.startsWith('WEBVTT')) {
      i++;
      continue;
    }

    // Optional cue id lines: numeric/alphanumeric only.
    if (!line.includes('-->') && !line.includes(':')) {
      i++;
      continue;
    }

    // Timing line
    if (line.includes('-->')) {
      const parts = line.split('-->');
      if (parts.length < 2) {
        i++;
        continue;
      }
      const startStr = parts[0]?.trim?.().split(' ')?.[0] ?? '';
      const endStr = parts[1]?.trim?.().split(' ')?.[0] ?? '';
      const start = parseTimestamp(startStr);
      const end = parseTimestamp(endStr);
      i++;


      // Collect following text lines until blank line
      const textLines: string[] = [];
      while (i < lines.length && lines[i]!.trim() !== '') {
        const t = lines[i]!.replace(/<[^>]+>/g, '').trim();
        if (t) textLines.push(t);
        i++;
      }

      const text = textLines.join(' ').trim();
      if (start != null && end != null && end > start && text) {
        cues.push({ start, duration: end - start, text });
      }
      continue;
    }

    i++;
  }

  return cues;
}

function parseYouTubeXmlCues(xmlText: string): Array<{ start: number; duration: number; text: string }> {
  const cues: Array<{ start: number; duration: number; text: string }> = [];

  // Try to parse with regex for typical caption xml.
  // Example: <text start="1234.0" dur="2.0">Hello</text>
  const re = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xmlText))) {
    const startMs = Number(m[1]);
    const dur = Number(m[2]);
    const rawText = m[3] ?? '';
    const text = rawText.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/</g, '<').replace(/>/g, '>').trim();
    if (!Number.isFinite(startMs) || !Number.isFinite(dur) || dur <= 0) continue;
    const start = startMs / 1000;
    cues.push({ start, duration: dur, text });
  }

  return cues;
}

async function extractTranscriptTrackData(_videoId: string): Promise<{ cues: any[]; language: string; isAutoGenerated: boolean } | null> {
  const w = window as any;
  const playerResponse = w.__ytInitialPlayerResponse || w.ytInitialPlayerResponse;
  const tracklist = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(tracklist) || !tracklist.length) return null;

  // Auto-preference: auto-generated (asr) first; then manual.
  const autoTrack = tracklist.find((t: any) => t?.kind?.toLowerCase() === 'asr')
    ?? tracklist.find((t: any) => t?.isAutoGenerated === true)
    ?? null;
  const manualTrack = tracklist.find((t: any) => t?.kind?.toLowerCase() === 'standard')
    ?? null;
  const chosen = autoTrack || manualTrack || tracklist[0];

  console.log('[YT StudyFlow][transcript] captionTracks selection:', {
    videoId: _videoId,
    trackCount: tracklist.length,
    autoTrackKind: autoTrack?.kind,
    manualTrackKind: manualTrack?.kind,
    chosenKind: chosen?.kind,
    chosenLanguage: chosen?.languageCode || chosen?.language,
    chosenIsAutoGenerated: chosen?.isAutoGenerated,
  });

  const language = (chosen?.languageCode || chosen?.language || 'en').toString();
  const isAutoGenerated = !!(autoTrack || chosen?.isAutoGenerated || chosen?.kind?.toLowerCase?.() === 'asr');

  const baseUrl = chosen?.baseUrl || chosen?.url || chosen?.baseUrlWithFormat;
  if (typeof baseUrl !== 'string' || !baseUrl) {
    console.warn('[YT StudyFlow][transcript] missing baseUrl for chosen track', {
      videoId: _videoId,
      chosen,
    });
    return null;
  }

  console.log('[YT StudyFlow][transcript] fetching transcript baseUrl:', { videoId: _videoId, baseUrl });

  const cues = await fetchCaptionTrackFromBaseUrl(baseUrl);
  if (Array.isArray(cues) && cues.length) {
    return { cues, language, isAutoGenerated };
  }

  return null;
}

function extractFromDOMAccessibility(_videoId: string): { cues: any[]; language: string; isAutoGenerated: boolean } | null {


  // DOM fallbacks: look for a visible transcript list. We avoid deep traversal.
  // If a transcript panel exists, it typically contains timestamps and text.
  const container = document.querySelector('[id*="transcript" i], ytd-transcript-renderer');
  if (!container) return null;

  const nodes = Array.from(container.querySelectorAll('span'));
  if (!nodes.length) return null;

  // This heuristic is weak; only parse if timestamps exist.
  const cues: Array<{ start: number; duration: number; text: string }> = [];
  // Try to find elements that have time markers.
  const timeSpans = Array.from(container.querySelectorAll('[class*="time" i], span'));

  for (const el of timeSpans) {
    const t = (el as HTMLElement).innerText?.trim?.() || '';
    if (!/^\d{1,2}:\d{2}(?::\d{2})?$/.test(t)) continue;

    // Find neighboring text node
    const parent = el.parentElement;
    const textCandidate = parent?.innerText?.replace?.(t, '').trim() ?? '';

    // parse hh:mm:ss
    const parts = t.split(':').map(x => parseInt(x, 10));
    let start = 0;
    if (parts.length === 2 && typeof parts[0] === 'number' && typeof parts[1] === 'number') start = parts[0] * 60 + parts[1];
    if (parts.length === 3 && typeof parts[0] === 'number' && typeof parts[1] === 'number' && typeof parts[2] === 'number') start = parts[0] * 3600 + parts[1] * 60 + parts[2];


    if (!textCandidate) continue;

    cues.push({ start, duration: 2.5, text: textCandidate });
  }

  if (cues.length) {
    return { cues, language: 'en', isAutoGenerated: false };
  }

  return null;
}

export async function fetchTranscriptChunks(videoId: string): Promise<ExtractResult> {
  const actualVideoId = videoId || extractVideoIdFromLocation();
  if (!actualVideoId) return { status: 'error', reason: 'Missing videoId' };

  // The parser expects a stable list of cues.
  // If cue extraction fails, we surface not-available / error gracefully.


  // Availability detection (fast)
  const avail = getTranscriptAvailabilityFromPage(actualVideoId);
  console.log('[YT StudyFlow][transcript] availability:', {
    videoId: actualVideoId,
    avail,
    url: window.location.href,
  });
  if (!avail.available) {
    return {
      status: 'not-available',
      reason: 'No captions/transcript tracks detected on page',
    };
  }

  // Try to extract already-parsed cues (best-case)
  try {
    const inMemory = await extractTranscriptTrackData(actualVideoId);
    if (inMemory?.cues?.length) {
      const parsed = parseYouTubeTranscript(actualVideoId, inMemory.cues);
      return {
        status: 'success',
        chunks: parsed.chunks,
        enhancedChunks: parsed.enhancedChunks,
        totalDuration: parsed.totalDuration,
        metadata: {
          videoId: actualVideoId,
          language: normalizeLanguage(inMemory.language),
          isAutoGenerated: !!inMemory.isAutoGenerated,
          fetchedAt: Date.now(),
          totalDuration: parsed.totalDuration,
          chunkCount: parsed.enhancedChunks.length,
        },
      };
    }


    // DOM accessibility fallback
    const dom = extractFromDOMAccessibility(actualVideoId);
    if (dom?.cues?.length) {
      const parsed = parseYouTubeTranscript(actualVideoId, dom.cues);
      return {
        status: 'success',
        chunks: parsed.chunks,
        enhancedChunks: parsed.enhancedChunks,
        totalDuration: parsed.totalDuration,
        metadata: {
          videoId: actualVideoId,
          language: normalizeLanguage(dom.language),
          isAutoGenerated: !!dom.isAutoGenerated,
          fetchedAt: Date.now(),
          totalDuration: parsed.totalDuration,
          chunkCount: parsed.enhancedChunks.length,
        },
      };
    }

    return { status: 'not-available', reason: 'Captions detected but cue extraction failed' };
  } catch (e: any) {
    return { status: 'error', reason: e?.message || String(e) };
  }
}

