import { create } from 'zustand';
import type { EnhancedTranscriptChunk, TranscriptChunk, TranscriptError } from '@/types/transcript';

import type { TranscriptStatus } from '@/types/transcript';

export type TranscriptAvailability = 'available' | 'no-transcript' | 'unknown';

export type TranscriptState = {
  currentVideoId: string | null;

  // Raw + enhanced chunks
  chunks: TranscriptChunk[];
  enhancedChunks: EnhancedTranscriptChunk[];

  // status
  status: TranscriptStatus;
  error: TranscriptError | null;
  availability: TranscriptAvailability;
  loading: boolean;

  // sync
  activeTime: number;
  activeChunkIndex: number;

  // search
  searchQuery: string;

  // derived, searchable list (for panel)
  filteredChunks: EnhancedTranscriptChunk[];

  // actions
  setVideoId: (videoId: string | null) => void;
  setSearchQuery: (query: string) => void;
  setTranscriptLoading: () => void;
  setTranscriptError: (error: TranscriptError, availability?: TranscriptAvailability) => void;
  setTranscriptNoAvailability: (reason?: string) => void;
  setTranscript: (params: {
    videoId: string;
    chunks: TranscriptChunk[];
    enhancedChunks: EnhancedTranscriptChunk[];
    totalDuration: number;
    language: string;
    isAutoGenerated: boolean;
    fetchedAt: number;
  }) => void;

  setActiveTime: (time: number, nextIndex: number) => void;
  scrollToActiveChunk: () => void;
};

function filterChunks(chunks: EnhancedTranscriptChunk[], query: string): EnhancedTranscriptChunk[] {
  const q = query.trim().toLowerCase();
  if (!q) return chunks;

  // Simple substring matching for Phase 1.
  // Later semantic embeddings can replace this while reusing the same store.
  return chunks.filter(c => c.text.toLowerCase().includes(q));
}

export const useTranscriptStore = create<TranscriptState>((set, get) => ({
  currentVideoId: null,

  chunks: [],
  enhancedChunks: [],

  status: 'idle',
  error: null,
  availability: 'unknown',
  loading: false,

  activeTime: 0,
  activeChunkIndex: -1,

  searchQuery: '',
  filteredChunks: [],

  setVideoId: (videoId) => {
    set({
      currentVideoId: videoId,
      status: 'idle',
      error: null,
      availability: 'unknown',
      loading: false,
      chunks: [],
      enhancedChunks: [],
      filteredChunks: [],
      activeTime: 0,
      activeChunkIndex: -1,
      searchQuery: '',
    });
  },

  setSearchQuery: (query) => {
    const { enhancedChunks } = get();
    set({
      searchQuery: query,
      filteredChunks: filterChunks(enhancedChunks, query),
    });
  },

  setTranscriptLoading: () => {
    set({
      status: 'loading',
      error: null,
      availability: 'unknown',
      loading: true,
      chunks: [],
      enhancedChunks: [],
      filteredChunks: [],
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setTranscriptError: (error, availability = 'unknown') => {
    set({
      status: 'error',
      error,
      availability,
      loading: false,
      chunks: [],
      enhancedChunks: [],
      filteredChunks: [],
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setTranscriptNoAvailability: () => {
    set({
      status: 'no-transcript',
      error: {
        type: 'not-available',
        message: 'Transcript unavailable for this video',
      },
      availability: 'no-transcript',
      loading: false,
      chunks: [],
      enhancedChunks: [],
      filteredChunks: [],
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setTranscript: ({
    videoId,
    chunks,
    enhancedChunks,
  }) => {
    const q = get().searchQuery;
    set({
      currentVideoId: videoId,
      status: 'success',
      error: null,
      availability: 'available',
      loading: false,
      chunks,
      enhancedChunks,
      filteredChunks: filterChunks(enhancedChunks, q),
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setActiveTime: (time, nextIndex) => {
    // Avoid rerender storms: only update if meaningful change.
    set((state) => {
      const activeChunkChanged = state.activeChunkIndex !== nextIndex;
      const timeChanged = Math.abs(state.activeTime - time) > 0.2;
      if (!activeChunkChanged && !timeChanged) return state;
      return {
        ...state,
        activeTime: time,
        activeChunkIndex: nextIndex,
      };
    });
  },

  scrollToActiveChunk: () => {
    const { activeChunkIndex, enhancedChunks } = get();
    if (activeChunkIndex < 0 || activeChunkIndex >= enhancedChunks.length) return;
    const id = enhancedChunks[activeChunkIndex]?.id;
    if (!id) return;

    const el = document.getElementById(`yt-studyflow-transcript-chunk-${id}`);
    if (!el) return;
    el.scrollIntoView({ behavior: 'smooth', block: 'center' });
  },
}));

