import { useCallback, useEffect } from 'react';

import { fetchTranscriptChunks } from '@/features/transcript/transcript.service';
import { useTranscriptStore } from '@/features/transcript/transcript.store';
import { findActiveChunkIndex } from '@/features/transcript/transcript.parser';

function useEventListener<T extends (...args: any[]) => any>(
  eventName: string,
  handler: T
): void {
  useEffect(() => {
    const wrapped = (e: Event) => {
      handler(e as any);
    };
    window.addEventListener(eventName, wrapped as any);
    return () => window.removeEventListener(eventName, wrapped as any);
  }, [eventName, handler]);
}

export function useTranscript(videoId: string): { loadTranscript: () => Promise<void> } {
  const {
    setVideoId,
    setTranscriptLoading,
    setTranscript,
    setTranscriptError,
    setTranscriptNoAvailability,
    setActiveTime,
    enhancedChunks,
  } = useTranscriptStore((s) => ({
    setVideoId: s.setVideoId,
    setTranscriptLoading: s.setTranscriptLoading,
    setTranscript: s.setTranscript,
    setTranscriptError: s.setTranscriptError,
    setTranscriptNoAvailability: s.setTranscriptNoAvailability,
    setActiveTime: s.setActiveTime,
    enhancedChunks: s.enhancedChunks,
  }));

  useEffect(() => {
    setVideoId(videoId);
  }, [videoId, setVideoId]);

  const loadTranscript = useCallback(async () => {
    if (!videoId) return;

    // Guard against stale in-flight requests when SPA navigation changes videoId.
    const requestId = `${videoId}:${Date.now()}`;
    (loadTranscript as any)._lastRequestId = requestId;

    setTranscriptLoading();

    const res = await fetchTranscriptChunks(videoId);

    // If another navigation triggered a new request, do not overwrite newer state.
    if ((loadTranscript as any)._lastRequestId !== requestId) return;

    if (res.status === 'not-available') {
      setTranscriptNoAvailability(res.reason);
      return;
    }

    if (res.status === 'error') {
      setTranscriptError({ type: 'unknown', message: res.reason });
      return;
    }

    setTranscript({
      videoId,
      chunks: res.chunks,
      enhancedChunks: res.enhancedChunks,
      totalDuration: res.totalDuration,
      language: res.metadata.language,
      isAutoGenerated: res.metadata.isAutoGenerated,
      fetchedAt: res.metadata.fetchedAt,
    });
  }, [videoId, setTranscript, setTranscriptError, setTranscriptLoading, setTranscriptNoAvailability]);

  // Transcript sync: listen to time update events emitted by youtubeEvents.ts
  useEventListener('yt-studyflow-time-update', useCallback((e: CustomEvent) => {
    const detail = e.detail as { currentTime: number; videoId: string };
    if (!detail || !detail.videoId) return;
    if (detail.videoId !== videoId) return;

    const time = detail.currentTime;
    const nextIndex = findActiveChunkIndex(enhancedChunks, time);
    setActiveTime(time, nextIndex);
  }, [videoId, enhancedChunks, setActiveTime]));

  return { loadTranscript };
}

