/**
 * Transcript type definitions
 */

export type TranscriptChunk = {
  text: string;
  start: number; // seconds
  duration: number; // seconds
};

/**
 * Enhanced transcript chunk with metadata
 */
export interface EnhancedTranscriptChunk extends TranscriptChunk {
  id: string;
  end: number; // start + duration
  index: number;
}

/**
 * Transcript metadata
 */
export interface TranscriptMetadata {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  fetchedAt: number; // timestamp
  totalDuration: number;
  chunkCount: number;
}

/**
 * Complete transcript with metadata
 */
export interface Transcript {
  metadata: TranscriptMetadata;
  chunks: EnhancedTranscriptChunk[];
}

/**
 * Transcript search result
 */
export interface TranscriptSearchResult {
  chunk: EnhancedTranscriptChunk;
  score: number; // relevance score
  highlightedText: string; // text with search term highlighted
}

/**
 * Transcript fetch status
 */
export type TranscriptStatus = 'idle' | 'loading' | 'success' | 'error' | 'no-transcript';

/**
 * Transcript error types
 */
export interface TranscriptError {
  type: 'network' | 'parsing' | 'not-available' | 'unknown';
  message: string;
}

